# Week 2 Summary
> NAME: $\color{red}{\text{    <Ryosuke Oguchi>     }}$
> 
> PID: $\color{red}{\text{    <A16777050>     }}$
>
> 
---

I certify that the following write-up is my own work, and have abided by the UCSD Academic Integrity Guidelines.

- [x] Yes
- [ ] No

% # %load tex-macros
<div hidden>
\newcommand{\require}[1]{}

$\require{begingroup}\require{newcommand}$
$\long\def \forcecommand #1{\providecommand{#1}{}\renewcommand{#1}}$
$\forcecommand{\defeq}{\stackrel{\small\bullet}{=}}$
$\forcecommand{\ra}{\rangle}$
$\forcecommand{\la}{\langle}$
$\forcecommand{\pr}{{\mathbb P}}$
$\forcecommand{\qr}{{\mathbb Q}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\av}{{\boldsymbol{a}}}$
$\forcecommand{\bv}{{\boldsymbol{b}}}$
$\forcecommand{\cv}{{\boldsymbol{c}}}$
$\forcecommand{\dv}{{\boldsymbol{d}}}$
$\forcecommand{\ev}{{\boldsymbol{e}}}$
$\forcecommand{\fv}{{\boldsymbol{f}}}$
$\forcecommand{\gv}{{\boldsymbol{g}}}$
$\forcecommand{\hv}{{\boldsymbol{h}}}$
$\forcecommand{\nv}{{\boldsymbol{n}}}$
$\forcecommand{\sv}{{\boldsymbol{s}}}$
$\forcecommand{\tv}{{\boldsymbol{t}}}$
$\forcecommand{\uv}{{\boldsymbol{u}}}$
$\forcecommand{\vv}{{\boldsymbol{v}}}$
$\forcecommand{\wv}{{\boldsymbol{w}}}$
$\forcecommand{\zerov}{{\mathbf{0}}}$
$\forcecommand{\onev}{{\mathbf{0}}}$
$\forcecommand{\phiv}{{\boldsymbol{\phi}}}$
$\forcecommand{\cc}{{\check{C}}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\Xv}{{\boldsymbol{X}\!}}$
$\forcecommand{\yv}{{\boldsymbol{y}}}$
$\forcecommand{\Yv}{{\boldsymbol{Y}}}$
$\forcecommand{\zv}{{\boldsymbol{z}}}$
$\forcecommand{\Zv}{{\boldsymbol{Z}}}$
$\forcecommand{\Iv}{{\boldsymbol{I}}}$
$\forcecommand{\Jv}{{\boldsymbol{J}}}$
$\forcecommand{\Cv}{{\boldsymbol{C}}}$
$\forcecommand{\Ev}{{\boldsymbol{E}}}$
$\forcecommand{\Fv}{{\boldsymbol{F}}}$
$\forcecommand{\Gv}{{\boldsymbol{G}}}$
$\forcecommand{\Hv}{{\boldsymbol{H}}}$
$\forcecommand{\alphav}{{\boldsymbol{\alpha}}}$
$\forcecommand{\epsilonv}{{\boldsymbol{\epsilon}}}$
$\forcecommand{\betav}{{\boldsymbol{\beta}}}$
$\forcecommand{\deltav}{{\boldsymbol{\delta}}}$
$\forcecommand{\gammav}{{\boldsymbol{\gamma}}}$
$\forcecommand{\etav}{{\boldsymbol{\eta}}}$
$\forcecommand{\piv}{{\boldsymbol{\pi}}}$
$\forcecommand{\thetav}{{\boldsymbol{\theta}}}$
$\forcecommand{\tauv}{{\boldsymbol{\tau}}}$
$\forcecommand{\muv}{{\boldsymbol{\mu}}}$
$%$
$\forcecommand{\sd}{\text{SD}}$
$\forcecommand{\se}{\text{SE}}$
$\forcecommand{\med}{\text{median}}$
$\forcecommand{\median}{\text{median}}$
$%$
$\forcecommand{\supp}{\text{supp}}$
$\forcecommand{\E}{\mathbb{E}}$
$\forcecommand{\var}{\text{Var}}$
$\forcecommand{\Ber}{{\text{Ber}}}$
$\forcecommand{\Bin}{{\text{Bin}}}$
$\forcecommand{\Geo}{{\text{Geo}}}$
$\forcecommand{\Unif}{{\text{Unif}}}$
$\forcecommand{\Poi}{{\text{Poi}}}$
$\forcecommand{\Exp}{{\text{Exp}}}$
$\forcecommand{\Chisq}{{\chi^2}}$
$\forcecommand{\N}{\mathbb{N}}$
$\forcecommand{\iid}{{\stackrel{iid}{\sim}}}$
$\forcecommand{\px}{p_{X}}$
$\forcecommand{\fx}{f_{X}}$
$\forcecommand{\Fx}{F_{X}}$
$\forcecommand{\py}{p_{Y}}$
$\forcecommand{\pxy}{p_{X,Y}}$
$\forcecommand{\po}{{p_0}}$
$\forcecommand{\pa}{{p_a}}$
$\forcecommand{\Xbar}{\overline{X}}$
$\forcecommand{\Ybar}{\overline{Y}}$
$\forcecommand{\Zbar}{\overline{Z}}$
$\forcecommand{\nXbar}{n \cdot \overline{X}}$
$\forcecommand{\nYbar}{n \cdot \overline{Y}}$
$\forcecommand{\nZbar}{n \cdot \overline{Z}}$
$\forcecommand{\Xn}{X_1, X_2, \dots, X_n}$
$\forcecommand{\Xm}{{X_1, X_2, \dots, X_m}}$
$\forcecommand{\Yn}{Y_1, Y_2, \dots, Y_n}$
$\forcecommand{\Ym}{{Y_1, Y_2, \dots, Y_m}}$
$\forcecommand{\sumXn}{X_1 + X_2 + \dots + X_n}$
$\forcecommand{\sumym}{Y_1 + Y_2 + \dots + Y_m}$
$\forcecommand{\la}{\ell_\alpha}$
$\forcecommand{\ua}{u_\alpha}$
$\forcecommand{\at}{{\alpha/2}}$
$\forcecommand{\mux}{\mu_{X}}$
$\forcecommand{\muy}{\mu_{Y}}$
$\forcecommand{\sx}{\sigma_{X}}$
$\forcecommand{\sy}{\sigma_{Y}}$
$\forcecommand{\ci}{\text{CI}}$
$\forcecommand{\pvalue}{$p$-value}$
$\forcecommand{\Ho}{H_{0}}$
$\forcecommand{\Ha}{H_{a}}$

\vskip-\parskip
\vskip-\baselineskip
</div>

In [1]:
import numpy as np
import scipy
from scipy import stats as stats

---

## Key Takeaways from Week 1


#### Tuesday: 

Lecture reviewed basic concepts of probability and the definitions regarding random variables. The key concepts that were applied throughout the distributions portion of the lecture were Probability Density Function (PDF), PMF, Variance, CDF, and Expected Value. The specific types of random variables were bernoulli, binomial, discrete uniform, possion. The continuous were continuous uniform, exponential random, normal, chi-squared, student-t, and F distribution.

#### Thursday

Lecture reviewed over the rest of the probability distributions that was not finished on Tuesday. To set up hypothesis testing, confidence intervals and quantiles were introduces as it was established that testing conclusions were shown to be subjective based off of the threshold that is chosen. A key point of this lecture is being able to illustrate the law of large numbers and central limit theroem through these different types of distributions.


---

## Tue, Apr 9th

#### Probability Review

Given a sample space $\mathcal{S}$ and an event $A$, there are three qualiatively different ways to define the probability $\pr(A)$:

**Empiricial Probability**


$$
\pr(A) = \text{times A occurs} \div \text{number of trials}
$$
An example of empirical probability is the following scenario:

> How many heads in 100 coin flips

**Theoretical Probability**


$$
\pr(A) = \text{Number of ways A can occur} \div \text{number of possible outcomes}
$$

An example of theoretical probability is the following scenario:

> How many ways a coin can land on heads out of 100 trials

**Subjective Probability**


$$
\pr(A) = \text{degree of belief that A will occur}
$$

#### Random Variables

Intuitively, a random variable $X$ is

a avariable whose value is a numerical outomce of a random phenomenon

and, the support of a random variable, denoted $\text{supp}(X)$, is

the set of all possible values it can take
- discrete random variable: random variable for which $\text{supp}(X)$ if finite or countably infinite number of values
- continuous random variable: a random varaible for which $\text{supp}(X)$ is infinite

A random variable $X$ can have different types of supports. 

1. cateogrical: different categories, no comparison
2. ordinal: different categories, can compare, but no quantifiable, discernable difference
3. discrete: support is a discrete collection of objectives where you can compare between categories and quality differences between them
4. continuous: support is a continuum

#### Properties of Random Variables

PMF of a discrete, random variable X is a function $p_x$ that gives probability that X is exactly equal to some value

Probability density function PDF of a continuous random variable X is a function $f_x$ that gives the probability that X is in a particular interval

**Cumulative Distribution Function**

Intuitively, the cumulative distribution function (CDF) of a random variable $X$ measures

probability that X is less than or equal to a particular value

For a random variable $X$ with PDF $\fx(x)$ the CDF $\Fx(x)$ is given by
$$
\Fx(x)  = \sum p_x(y) \text{  if discrete} \\ \int _\text{-inf}^x\text f_x(y)dy\text{  if continuous}\tag{formula for CDF of continuous RV}
$$

**Expected value**

For a random variable $X$ with PMF $\px$ or with PDF $\fx$, the expected value of $X$ is

$$
\E(X)  = \sum x \cdot p_x(x) \tag{formula for PMF}
$$
$$
\E(X)  = \int _\text{-inf}^\text{inf} x \cdot f_x(x)dx \tag{formula for PDF}
$$

**Variance**

For a random variable $X$ with expected value $\E(X)$ and second moment $\E(X^2)$, the variance of $X$ is


$$
\var(X)  = \E ((X-\E(X))^2)  = \E(X^2) - \E(X)^2\tag{formula for variance}
$$

In [2]:
x = stats.poisson(2)
ex1 = x.expect()
ex2 = x.moment(2)
varx = x.var()
varx

2.0

#### Examples of Probability Distributions

---

§1. Bernoulli distribution

A random variable $X \sim \Ber(p)$ follows a Bernoulli distribution with parameter ... 

* The support is
$$
\supp(X) = 0,1
$$
* The PMF is 
$$
\px(x) =  p \text{ if } x = 1 \\ 1-p \text{ if } x = 0
$$
* The expected value is
$$
\mathbb E(X) = p
$$
* The variance is
$$
\var(X) = p(1-p)
$$

In python, we can generate $10$ random samples from a Bernoulli distribution as follows:

In [18]:
X = stats.bernoulli(0)
X.rvs(10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

If is binomial, you look N, independent random random variables

---

§2. Discrete Uniform distribution

A random variable $X \sim \Unif \{a, b\}$ follows a _discrete uniform_ distribution with parameter(s) a, b

* The support is

$$
\supp(X) = a, a+1, a+2, \dots, b
$$

* The PMF is 
$$
p_X(x) = \begin{cases}
\displaystyle\frac{1}{b-a+1} & \text{if } x = a, a+1, a+2, \dots, b \\ \\
0 & \text{otherwise}
\end{cases}
$$
* The expected value is
$$
\mathbb E(X) = \frac{a+b}{2}
$$
* The variance is
$$
\var(X) = \quad \text{Var}(X) = \frac{(b-a+1)^2 - 1}{12}
$$

We can generate $10$ random samples from a discrete uniform distribution as follows:

In [15]:
X = stats.randint(0, 10)
X.rvs(10)

array([2, 3, 4, 5, 4, 0, 7, 9, 7, 1], dtype=int64)

---

§3. Poisson Distribution

A random variable $X \sim \Poi(\lambda)$ follows a _Poisson_ distribution with parameter(s) ... 

* The support is
$$
\supp(X) = 0,1,2,...
$$
* The PMF is 
$$
\px(x) = p_X(x) = \begin{cases}
\displaystyle\frac{\lambda^x}{x!} e^{-\lambda} & \text{if } x = 0, 1, 2, \dots \\
0 & \text{otherwise}
\end{cases}
$$
* The expected value is
$$
\mathbb E(X) = \lambda
$$
* The variance is
$$
\var(X) = \lambda
$$

We can generate $10$ random samples from a Poisson distribution as follows:

In [14]:
X = stats.poisson(10)
X.rvs(10)

array([17, 13,  9,  8, 17, 15,  7, 11, 10, 10], dtype=int64)

---

§4. Exponential distribution

A random variable $X \sim \Exp(\lambda)$ follows an _Exponential_ distribution with parameter(s) ... 

* The support is
$$
\supp(X) = 0, \text{inf}
$$
* The PDF is 
$$
\fx(x) = f_X(x) = \begin{cases}
\lambda e^{-\lambda x} & \text{if } x \geq 0 \\
0 & \text{otherwise}
\end{cases}
$$
* The expected value is
$$
\mathbb E(X) = \frac{1}{\lambda}
$$
* The variance is
$$
\var(X) = \frac{1}{\lambda ^ 2}
$$

We can generate $10$ random samples from an Exponential distribution as follows:

In [13]:
X = stats.expon(loc=0, scale=1/10)
X.rvs(10)

array([0.13255687, 0.16653288, 0.14854583, 0.12451428, 0.126786  ,
       0.01681222, 0.17046501, 0.05988929, 0.20430701, 0.01126647])

---

§5. Normal Distribution

A random variable $X \sim N(\mu, \sigma^2)$ follows a Normal distribution with parameter(s) ... 

* The support is
$$
\supp(X) = - inf, inf
$$
* The PDF is 
$$
\fx(x) = ...
$$
* The expected value is
$$
\mathbb E(X) = \mu
$$
* The variance is
$$
\var(X) = \sigma ^ 2
$$

We can generate $10$ random samples from a Normal distribution as follows:

In [7]:
X = stats.norm(0,1)
X.rvs(10)

array([-2.00036099, -0.08468246,  0.14120056, -1.02336663,  0.53855285,
       -2.00198783, -1.01243635, -1.54280403, -1.7939681 , -0.9275237 ])

---

§6. Chi-squared Distribution

A random variable $X \sim \chi^2(k)$ follows a Chi-squared distribution with parameter(s) ... 

* The support is
$$
\supp(X) = 0, inf
$$
* $X \sim \chi^2(k)$ is obtained using $k$ iid copies of a standard normal random variable $Z_1, Z_2, \dots, Z_k \sim N(0, 1)$ as follows:
$$
X = \sum _i ^ k Z_i^2
$$
* The expected value is
$$
\mathbb E(X) = k
$$
* The variance is
$$
\var(X) = 2k
$$

We can generate $10$ random samples from a Chi-squared distribution as follows:

In [10]:
X = stats.chi2(12)
X.rvs(10)

array([15.72927815, 10.16536728,  8.67480187, 14.27312884, 13.23736865,
       11.26010229, 12.67247026, 16.45655   , 15.21285663,  6.33891765])

---

§7. Student's t Distribution

A random variable $X \sim t(k)$ follows a Student's $t$ distribution with parameter(s) ... 

* The support is
$$
\supp(X) = - inf, inf
$$

* Given $Z \sim N(0,1)$ and $Y \sim \chi^2(k)$ with $Z \perp Y$, a Student's $t$ random variable $X$ is obtained as follows:
$$
X = \frac{Z}{\sqrt{\frac{Y}{k}}}
$$


We can generate $10$ random samples from a Student's $t$ distribution as follows:

In [20]:
X = stats.f(100,10)
X.rvs(10)

array([0.988327  , 1.16861379, 0.94532124, 1.33733059, 1.1597979 ,
       1.07890427, 0.89272295, 3.14287769, 1.40896425, 1.54604134])

---

§8. $F$ Distribution

A random variable $X \sim F(k_1, k_2)$ follows an $F$ distribution with parameter(s) ... 

* The support is
$$
\supp(X) = (0,inf)
$$

* Given $Y \sim \chi^2(k_1)$ and $Z \sim \chi^2(k_2)$ with $Y \perp Z$, an $F$ random variable $X$ is obtained as follows:
$$
X = ~ F(k_1, k_2) = \frac{\frac{Y}{k_1}}{\frac{Z}{k_2}} \\ \text{where } Y \sim Chi Sq(k_1) \text{ and } Z \sim Chi sq(k_2)
$$

We can generate $10$ random samples from a Normal distribution as follows:

In [6]:
X = stats.norm(0,1)
X.rvs(10)

array([ 0.66749345, -0.06552266, -0.21882351,  0.37319806, -0.83579178,
        2.12759851,  0.527229  ,  1.27883428, -0.74842182, -0.74602191])

CDF corresponds to integral of the Normal distribution

<h3>Quantile</h3>

Given a random varaible X ~ D and a number aplha, the a-quantile of X is avalue of $q_a$ such that

$$
P(X \le q_\alpha) = \alpha
$$

In terms of CDF, this is 
$$
F_x(q_\alpha) = \alpha
$$
$q_a$ is the value such that probability that X is less than or equal to $q_a$ is exactly $\alpha$

<h3>Empirical CDF</h3>
Empirical CDF is given by 

$$
F_n(x) = \frac{1}{n} \sum _{i=1} ^ n I (X_i \le x) \\
$$
Indicator function classifies X as 1 or 0

Corresponding quantile is the empirical quantile $(100 \times \alpha)$


---

Suppose $X_1, X_2, \dots, X_n$ are $n$ iid samples from a distribution with mean $\E(X) = M$ and variance $\var(X) = V$.

Let $$\Xbar = \frac{1}{n} \sum_{i=1}^n X_i$$ be the sample mean and $$S^2 = \frac{1}{n-1} \sum_{i=1}^n (X_i - \Xbar)^2$$ be the sample variance.

**Law of large Numbers**

In english, the law of large numbers says that

As the number of observations increases, the average of the observed value gets closer to the expected value

$$
\Xbar = \frac{1}{n} \sum_{i=1}^n X_i = \E(X)
$$ 
as X -> inf


**Central Limit Theorem**

In english, the central limit theorem says that

$$\frac{\Xbar - \E(X)}{\sqrt{\text{Var}}(X)} \text{ Looks like } N(0,1)$$ 
as n-> Inf

---
---

## Thu, Apr 11th

#### Statistic

Suppose $\Xn$ is sampled iid from a distribution $D(\theta)$ where $\theta$ is ...

Then, intuitively, a statistic $\hat\theta \equiv \hat\theta(\Xn)$ is ...


#### Sampling Distribution

Since $\Xn$ are all random variables, the statistic $\hat\theta$ is also a statistic computed from sample $X_1, X_2,...,X_n$. This is the best guess for parameter $\theta$. As X_1, X_2,...,X_n are random, $\hat\theta$ is also random.

In words, the sampling distribution of $\hat\theta$ is the distribution of $\hat\theta$ when $X_1, X_2,...,X_n$ are drawn from $D(\theta)$

#### Intuition behind Sampling Distributions

If we call the process of sampling $\Xn$ from $D(\theta)$ as a "**random experiment**", then let

* $\hat\theta^{(1)}, \hat\theta^{(1)}, \dots, \hat\theta^{(N)}$ be the statistics obtained from each of $N$ random experiments.

Then, the sampling distribution of $\hat\theta$ roughly is like the true sampling distribution.

- Bernouli distribution looks like binomial distribution as the number N increases
- Distribution of sample mean looks like normal distribution as N increases
- Sample mean for Exponentional distribution looks like gamma distribution looks like exponential distribution

---

#### Confidence Interval

The **$100 \times (1-\alpha)\%$ confidence interval** for a parameter $\theta$ is an interval $[\la, \ua]$ such that:

$$
P(l_\alpha \le \hat\theta \le u_a) = 1 - \alpha 
$$

we denote this as $\ci(\theta) = [\la, \ua]$.

For a statistic $\hat\theta$ with standard error $\se(\hat\theta)$ the general formula for the $100 \times (1-\alpha)\%$ confidence interval is given by


$$
\ci(\theta, \alpha) = [\hat\theta - q_a/2 * SE(\hat\theta), \hat\theta + q_a/2 * SE(\hat\theta)]
$$

#### Interpretation of Confidence Intervals

If we call the process of sampling $\Xn$ from $D(\theta)$ as a "**random experiment**" where $\theta^*$ is the true, unknown population parameter.  

Let

$$
[\la^{(1)}, \ua^{(1)}], [\la^{(2)}, \ua^{(2)}], \dots, [\la^{(N)}, \ua^{(N)}]
$$

be the $100 \times (1-\alpha)\%$ confidence intervals obtained from each of $N$ random experiments.




Then, the guarantee provided by the construction of the confidence interval is that 

the value such that the probability that $X$ is less than or equal to $q_\alpha$ is exactly $\alpha$.

Given n=100 and result is 1 or 0, and $\theta=0.646$; the distribution is $\text{Ber}(\theta)$
- Sample mean is best guess for $\hat\theta$
- Use confidence interval, different samples will result in different values of $\hat\theta$
- Average can be sensisitve to bad samples

---

#### Examples of Confidence Intervals (from Math 183 or equivalent)

---

§1. One sample Proportion

| Description | Answer |
|:---|:---|
| Assumption | $\Xn \sim ...$ |
| Population parameter | $\theta = \mu$ |
| Statistic | $\hat\theta = \bar{X}$ |
| Standard Error | $\se(\hat\theta) = \frac{\sigma}{\sqrt{n}} $|
| Sampling distribution | $D_{\hat\theta} = \text{Normal}(\mu, \frac{\sigma^2}{n})$ |

The **99\% confidence interval** for $\theta$ is given by

$$
\ci(\theta, \alpha) = [\hat\theta - z_a/2 \sqrt{\frac{\hat\theta(1-\hat\theta)}{n}}, \hat\theta + z_a/2 \sqrt{\frac{\hat\theta(1-\hat\theta)}{n}} ]
$$

---

§2. Difference of two proportions

| Description | Answer |
|:---|:---|
| Assumption | $\Xn \sim \text{Binomial}(n_1, p_1)$ and $\Ym \sim \text{Binomial}(n_2, p_2)$|
| Population parameter | $\theta = p_1 - p_2$  |
| Statistic | $\hat\theta = \hat{p}_1 - \hat{p}_2$ |
| Standard Error | $\se(\hat\theta) = \sqrt{\frac{\hat{p}_1(1 - \hat{p}_1)}{n_1} + \frac{\hat{p}_2(1 - \hat{p}_2)}{n_2}}$ |
| Sampling distribution | $D_{\hat\theta} = \text{Normal}\left(p_1 - p_2, \sqrt{\frac{p_1(1 - p_1)}{n_1} + \frac{p_2(1 - p_2)}{n_2}}\right)$ |

The **97\% confidence interval** for $\theta$ is given by

$$
\ci(\theta, \alpha) = \theta\hat ±z _{α/2} ×\se(\theta\hat)$$

---

§3. One sample Mean (with unknown variance)

| Description | Answer |
|:---|:---|
| Assumption | $\Xn \sim \text{Normal}(\mu, \sigma^2)$ |
| Population parameter | $\theta = \mu$ |
| Statistic | $\hat\theta = \bar{X}$ |
| Standard Error | $\se(\hat\theta) = \frac{s}{\sqrt{n}}$ |
| Sampling distribution | $D_{\hat\theta} = \text{Student's t-distribution with } (n-1) \text{ degrees of freedom}$ |

The **93\% confidence interval** for $\theta$ is given by

$$
\ci(\theta, \alpha) = θ ±t _{\alpha/2,n−1} ×\se(\theta\hat )
$$

---

§1. Difference of two means (with unknown variances)

| Description | Answer |
|:---|:---|
| Assumption | $\Xn \sim \text{Normal}(\mu_1, \sigma_1^2)$ and $\Ym \sim \text{Normal}(\mu_2, \sigma_2^2)$ |
| Population parameter | $\theta = \mu_1 - \mu_2$ |
| Statistic | $\hat\theta = \bar{X}_1 - \bar{X}_2$ |
| Standard Error | $\se(\hat\theta) = \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}$ |
| Sampling distribution | $D_{\hat\theta} = \text{Student's t-distribution with } \nu \text{ degrees of freedom}$ |

The **96\% confidence interval** for $\theta$ is given by

$$
\ci(\theta, \alpha) = \hat\theta±t _{α/2,ν} × \se(\theta\hat)
$$

---