# Week 1 Summary
> NAME: $\color{red}{\text{    Ryosuke Oguchi     }}$
> 
> PID: $\color{red}{\text{    A16777050     }}$
>
> 
---

I certify that the following write-up is my own work, and have abided by the UCSD Academic Integrity Guidelines.

- [x] Yes
- [ ] No

% # %load tex-macros
<div hidden>
\newcommand{\require}[1]{}

$\require{begingroup}\require{newcommand}$
$\long\def \forcecommand #1{\providecommand{#1}{}\renewcommand{#1}}$
$\forcecommand{\defeq}{\stackrel{\small\bullet}{=}}$
$\forcecommand{\ra}{\rangle}$
$\forcecommand{\la}{\langle}$
$\forcecommand{\pr}{{\mathbb P}}$
$\forcecommand{\qr}{{\mathbb Q}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\av}{{\boldsymbol{a}}}$
$\forcecommand{\bv}{{\boldsymbol{b}}}$
$\forcecommand{\cv}{{\boldsymbol{c}}}$
$\forcecommand{\dv}{{\boldsymbol{d}}}$
$\forcecommand{\ev}{{\boldsymbol{e}}}$
$\forcecommand{\fv}{{\boldsymbol{f}}}$
$\forcecommand{\gv}{{\boldsymbol{g}}}$
$\forcecommand{\hv}{{\boldsymbol{h}}}$
$\forcecommand{\nv}{{\boldsymbol{n}}}$
$\forcecommand{\sv}{{\boldsymbol{s}}}$
$\forcecommand{\tv}{{\boldsymbol{t}}}$
$\forcecommand{\uv}{{\boldsymbol{u}}}$
$\forcecommand{\vv}{{\boldsymbol{v}}}$
$\forcecommand{\wv}{{\boldsymbol{w}}}$
$\forcecommand{\zerov}{{\mathbf{0}}}$
$\forcecommand{\onev}{{\mathbf{0}}}$
$\forcecommand{\phiv}{{\boldsymbol{\phi}}}$
$\forcecommand{\cc}{{\check{C}}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\Xv}{{\boldsymbol{X}\!}}$
$\forcecommand{\yv}{{\boldsymbol{y}}}$
$\forcecommand{\Yv}{{\boldsymbol{Y}}}$
$\forcecommand{\zv}{{\boldsymbol{z}}}$
$\forcecommand{\Zv}{{\boldsymbol{Z}}}$
$\forcecommand{\Iv}{{\boldsymbol{I}}}$
$\forcecommand{\Jv}{{\boldsymbol{J}}}$
$\forcecommand{\Cv}{{\boldsymbol{C}}}$
$\forcecommand{\Ev}{{\boldsymbol{E}}}$
$\forcecommand{\Fv}{{\boldsymbol{F}}}$
$\forcecommand{\Gv}{{\boldsymbol{G}}}$
$\forcecommand{\Hv}{{\boldsymbol{H}}}$
$\forcecommand{\alphav}{{\boldsymbol{\alpha}}}$
$\forcecommand{\epsilonv}{{\boldsymbol{\epsilon}}}$
$\forcecommand{\betav}{{\boldsymbol{\beta}}}$
$\forcecommand{\deltav}{{\boldsymbol{\delta}}}$
$\forcecommand{\gammav}{{\boldsymbol{\gamma}}}$
$\forcecommand{\etav}{{\boldsymbol{\eta}}}$
$\forcecommand{\piv}{{\boldsymbol{\pi}}}$
$\forcecommand{\thetav}{{\boldsymbol{\theta}}}$
$\forcecommand{\tauv}{{\boldsymbol{\tau}}}$
$\forcecommand{\muv}{{\boldsymbol{\mu}}}$
$%$
$\forcecommand{\sd}{\text{SD}}$
$\forcecommand{\se}{\text{SE}}$
$\forcecommand{\med}{\text{median}}$
$\forcecommand{\median}{\text{median}}$
$%$
$\forcecommand{\Ber}{{\text{Ber}}}$
$\forcecommand{\Bin}{{\text{Bin}}}$
$\forcecommand{\Geo}{{\text{Geo}}}$
$\forcecommand{\Unif}{{\text{Unif}}}$
$\forcecommand{\Poi}{{\text{Poi}}}$
$\forcecommand{\Exp}{{\text{Exp}}}$
$\forcecommand{\Chisq}{{\chi^2}}$
$\forcecommand{\N}{\mathbb{N}}$
$\forcecommand{\iid}{{\stackrel{iid}{\sim}}}$
$\forcecommand{\px}{p_{X}}$
$\forcecommand{\fx}{f_{X}}$
$\forcecommand{\Fx}{F_{X}}$
$\forcecommand{\py}{p_{Y}}$
$\forcecommand{\pxy}{p_{X,Y}}$
$\forcecommand{\po}{{p_0}}$
$\forcecommand{\pa}{{p_a}}$
$\forcecommand{\Xbar}{\overline{X}}$
$\forcecommand{\Ybar}{\overline{Y}}$
$\forcecommand{\Zbar}{\overline{Z}}$
$\forcecommand{\nXbar}{n \cdot \overline{X}}$
$\forcecommand{\nYbar}{n \cdot \overline{Y}}$
$\forcecommand{\nZbar}{n \cdot \overline{Z}}$
$\forcecommand{\Xn}{X_1, X_2, \dots, X_n}$
$\forcecommand{\Xm}{{X_1, X_2, \dots, X_m}}$
$\forcecommand{\Yn}{Y_1, Y_2, \dots, Y_n}$
$\forcecommand{\Ym}{{Y_1, Y_2, \dots, Y_m}}$
$\forcecommand{\sumXn}{X_1 + X_2 + \dots + X_n}$
$\forcecommand{\sumym}{Y_1 + Y_2 + \dots + Y_m}$
$\forcecommand{\la}{\ell_\alpha}$
$\forcecommand{\ua}{u_\alpha}$
$\forcecommand{\at}{{\alpha/2}}$
$\forcecommand{\mux}{\mu_{X}}$
$\forcecommand{\muy}{\mu_{Y}}$
$\forcecommand{\sx}{\sigma_{X}}$
$\forcecommand{\sy}{\sigma_{Y}}$
$\forcecommand{\pvalue}{$p$-value}$
$\forcecommand{\Ho}{H_{0}}$
$\forcecommand{\Ha}{H_{a}}$

\vskip-\parskip
\vskip-\baselineskip
</div>

---

## Key Takeaways from Week 1


#### Tuesday: 

Overview of the syllabus, policies, expectations; moreover, the background of statistical inference in the lens of history. The main example that was used to illustrate this fact was to present a hypothesis test problems in the tea vs milk ordering.

#### Thursday

A summary of basic python operations, markdown, Latex, and review of linear algebra. A large portion of the lecture covered linear algebra concepts in regards to vector and matrix operations. This means review of vectors and corresponding python use. Operations included dot and cross product and the python application used in them. Finally, there was a breif review on eigenvalues and eigenvectors and how to generate them using the numpy package in python.


---

## Tue, Apr 2nd

### Basics of markdown

**Bullet Lists and Numbered Lists**

This is a bullet list:

* Item 1
    - Subitem 1
    - Subitem 2
* Item 2
* Item 3

This is a numbered list:
1. Number 1
    1. Section a
    1. Section b
2. Number 2
3. Number 3


**Math**

In-line expression $1+1=2$ wrap the expression around dollar signs

$x_1^2$ this is subscripts and exponents

$x^2_1$ order of exponent and underscore does not matter

$\beta$ write out the symbol with backslash

$$
x+1=5
$$
Double dollar creates its own line

$$
\overline{X} = \frac{1}{n}\sum_{i=1}^n X_i \\
\text{Var}(X) = \frac{1}{n}\sum_{i=1}^n (X_i - \overline{X})^2

$$

**Boxed & Colored Equations**

$$
\boxed{
    \color{skyblue}
    {\frac{1}{n}\sum_{i=1}^n X_i = \overline{X}}}
$$

**Math Macros**

$$
\newcommand{\newsum}[2]{\sum_{i=#1}^{#2}}
\newsum{0}{m} a_i
$$

$$
\newcommand{\Xn}{X_1, X_2, \cdots, X_n}
\Xn \text{ is sampled iid from a distribution }
D(\theta)
$$

---

## Thu, Apr 4th

### Data types

In [2]:
type(19)

int

In [3]:
float(10)

10.0

### Operations

In [4]:
4/2

2.0

In [5]:
3%2

1

In [6]:
7//3

2

In [7]:
5 ** 2

25

### Data structures

In [8]:
[1,2]

[1, 2]

In [9]:
[1, 2] + [3,4]

[1, 2, 3, 4]

In [10]:
(1,2,3)

(1, 2, 3)

In [11]:
{"One": 1, "Two": 2, "Three": 3}.keys()

dict_keys(['One', 'Two', 'Three'])

In [12]:
set([1,1,1,1,1])

{1}

In [13]:
{1,2,3, 1, 1}

{1, 2, 3}

In [14]:
a = {1,2,3}
b = {2,3,7}
b.issubset(a)

False

In [15]:
a.difference(b)

{1}

In [16]:
a.symmetric_difference(b)

{1, 7}

In [17]:
arb_cond = False
def cond_func():
    if arb_cond:
        return "Here!"
    else:
        return "Nope"


In [18]:
cond_func()

'Nope'

In [19]:
arb_cond = True
cond_func()

'Here!'

In [20]:
x = 10
while x > 0:
    print(x)
    x -= 1

10
9
8
7
6
5
4
3
2
1


**Vectors**

$$
<3,4>
$$

A vector in n dimensional space where $v_i$ is a number

$\vec{v}$

When you add two vectors ...

$\vec{v} + \vec{w} = (v_1+w_1, v_2+v_2, ..., v_d + w_d)^T$

In [21]:
import numpy as np
x = np.array([3,4])
y = np.array([1,2])
x+y

array([4, 6])

When you multiply a vector by a scalar ...

$\vec{v} \vec{w} = \sum_{i=1}^n u_iv_i$ This is a dot product

You can "multiply" two vectors in two different ways:

1. Dot Product
2. Cross Product 

Cross product is perpendicular to linear space spanned by $\vec{v}$ and  $\vec{w}$

$$
w \perp \text{span}\{u,v\}
$$
magnitude:
$$
\|w\| = \|u\| \|v\| \sin\big(\angle\theta(u,v)\big)
$$

In [22]:
np.dot(x,y)

11

In [23]:
np.cross(x,y)

array(2)

**Matrices**

Intuitively, a matrix is ...

Transformation of a vector $\vec{v}$ by a matrix spanning $m \times n$ matrix

When a matrix acts on a vector, you get ...

In [24]:
import numpy as np

# Creating vectors and matrices
vector = np.array([1,2])
matrix = np.array([
    [1,-1],
    [-1,1]
])

# Calculating the product
product = np.dot(x,y)
product

11

In [25]:
A = np.array([[1,-1], [-1,1]])
v = np.array([2,3])

A @ v

array([-1,  1])

In [26]:
A @ A

array([[ 2, -2],
       [-2,  2]])

**Basic linear algebra operations:**
1. Norm: $||v|| = \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}$
2. Dot product: $\vec{u} \cdot \vec{v}$ = $u_1 v_1 + u_2 v_2 + ... u_n v_n$
4. Matrix transpose: $(1 2 3)$ to $\begin{pmatrix}1 \\ 2\\ 3\\ \end{pmatrix}$
5. Matrix inverse: $A^{-1}$ = $\frac{1}{\text{det}(A)} \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}^{-1}$

**Slightly more advanced linear algebra operations**

If we're given a system of equations, for example, 

$$
\begin{align*}
2x + 3y &= 5 \\
4x + 5y &= 6
\end{align*}
$$

We can represent it in the matrix-vector form as ...

$$
b =
\begin{pmatrix}
5 \\
6 \\
\end{pmatrix}
\quad
A = 
\begin{pmatrix}
2 & 3\\
4 & 5
\end{pmatrix}
$$

The solution for the unknown variables, $(x, y)$ is given by ...

$$
\quad
x = \begin{pmatrix}
x \\
y \\
\end{pmatrix}
$$

Solution:

$$
x = A^{-1}b
$$

In code, we can do this as follows: ...

In [31]:
# Solving a system of linear equations
A = np.array([
            [2,3],
            [4,5]
            ])
b = np.array([5,6])
solution = np.linalg.solve(A,b)
solution

array([-3.5,  4. ])

---

**Eigenvalues and eigenvectors**

Given an $n \times n$ matrix $A$, the eigenvalue of $A$ is the scalar $\lambda$ such that ...

$Av = \lambda v$ and $\lambda$ is a vector. Vectors $\vec{v}$ are eigenvectors and the corresponding scalars are $\lambda$ are eigenvalues

The eigenvector of $A$ is the vector $v$ such that ...

vector $v$ is associated with the matrix $A$ such that when $A$ is applied to $v$, the result is a scale multiple

Intuitively, the eigenvector of a matrix describes ...

the direction of the components that allows square matrix $A$ to equal to the corresponding scalars $v$

In code, we can compute the eigenvalues and eigenvectors of a matrix as follows:

In [57]:
A = np.random.randn(2,2)

eigenvalues, eigenvectors = np.linalg.eig(A)

In [58]:
eigenvalues, eigenvectors

(array([2.10093616, 0.00603328]),
 array([[ 0.77743832,  0.45630509],
        [-0.62895918,  0.88982339]]))

We can verify that the eigenvalues and eigenvectors are correct by running the following code and ensuring that the output matches the expected values:


In [59]:
lambda1 = eigenvalues # Largest eigenvalue
v1 = eigenvectors # Corresponding eigenvector


# Expected value of Av
expected_value = lambda1 * v1

# Actual value of Av
Av = A @ v1

# Check if the expected value and actual value are equal
np.allclose(expected_value, Av)

True